### ISSUE TITLE
Please add support for TVR TS0601 _TZE200_sur6q7ko

### ISSUE THREAD

**Issue by malfunctioningEddy** [jacekk015/zha_quirks#4]
Hi,

Sorry to maybe misuse this thead. 

Very new to the whole quirk functionality in HA. All my devices were recognised perfectly in the past untill I bought some TVR's.
Could you point me to the correct place to request that my device can be added to a quirk or should I first test it with a custom quirk?

Device: TS0601 by _TZE200_sur6q7ko

_Originally posted by @malfunctioningEddy in https://github.com/jacekk015/zha_quirks/issues/1#issuecomment-1407379415_

**Comment by malfunctioningEddy** [comment]
Diagnostic:
[zha-aa64a7367a57a35c45ede02f9329a924-_TZE200_sur6q7ko TS0601-95a0ad68a5ae486737293ba12b16397b.json_diagnostic.txt](https://github.com/jacekk015/zha_quirks/files/10527906/zha-aa64a7367a57a35c45ede02f9329a924-_TZE200_sur6q7ko.TS0601-95a0ad68a5ae486737293ba12b16397b.json_diagnostic.txt)

Signature:
[signature.txt](https://github.com/jacekk015/zha_quirks/files/10527907/signature.txt)

Log after putting HA in debug:
[home-assistant_2023-01-28T17-47-52.687Z.log](https://github.com/jacekk015/zha_quirks/files/10527909/home-assistant_2023-01-28T17-47-52.687Z.log)

**Comment by malfunctioningEddy** [comment]
What I found is that in debug mode the device looks different:
Debug:
![afbeelding](https://user-images.githubusercontent.com/98105177/215283598-b9fd49e5-5d32-4a25-b901-8beb7ab71694.png)

Normal:
![afbeelding](https://user-images.githubusercontent.com/98105177/215283682-155b36f0-7499-4b27-a017-c78586bc42c0.png)

**Comment by jacekk015** [comment]
Enable "custom_quirks_path"
https://github.com/jacekk015/zha_quirks#usage

Download file: https://github.com/jacekk015/zha_quirks/blob/main/ts0601_trv_zonnsmart.py
and put it in that folder.
Restart HA and re-pair device again.
In case of errors post FULL HA log file.

**Comment by malfunctioningEddy** [comment]
Thanks for making this easy.  Again, I'm learning.
Will try this evening and report back.

**Comment by malfunctioningEddy** [comment]
Hi I managed to do a first test.
After completing all the steps I restarted Home Assistant.
ZHA failed to set up however:
![firefox_9u79F4O7i2](https://user-images.githubusercontent.com/98105177/215570796-e87ed7ee-6cc4-43f7-ae60-af2e5ac7e205.png)

Log view:
![firefox_w07PDAblgj](https://user-images.githubusercontent.com/98105177/215570854-6f7c03b9-0e55-48e6-8995-03fd401f6cac.png)

Full logs:
[home-assistant_2023-01-30T19-07-00.508Z.log](https://github.com/jacekk015/zha_quirks/files/10539122/home-assistant_2023-01-30T19-07-00.508Z.log)

**Comment by MattWestb** [comment]
Something is bad in the local quirk:
```
  File "/usr/local/lib/python3.10/site-packages/zigpy/quirks/__init__.py", line 34, in get_device
    return _DEVICE_REGISTRY.get_device(device)
  File "/usr/local/lib/python3.10/site-packages/zigpy/quirks/registry.py", line 148, in get_device
    device = candidate(device._application, device.ieee, device.nwk, device)
  File "/config/custom_zha_quirks/ts0601_trv_zonnsmart.py", line 164, in __init__
    self.ZONNSMARTManufCluster_bus = Bus()
```
I think @jacekk015 is fixing it then hi have time.

What version of HA is you running ?

**Comment by malfunctioningEddy** [comment]
Hi,

I'm running:
![image](https://user-images.githubusercontent.com/98105177/215576422-55ef0840-4821-4757-8947-57e116539121.png)

**Comment by malfunctioningEddy** [comment]
Hi,

I would like to run another test if that is possible. Just upgraded to:
![image](https://user-images.githubusercontent.com/98105177/216308880-b14c389e-90ce-4ced-9f5a-16bd04f82d1e.jpeg)

But seems the device was not added yet. How can I find out in which release it will be?

**Comment by malfunctioningEddy** [comment]
@jacekk015 , @MattWestb 

Hi again, just performed another test with a custom quirk.
Downloaded the ts0601_trv_zonnsmart.py file again and put it in correct directory.

Tried to add the device but HA remained configuring.
![firefox_j03Qh0s5zP](https://user-images.githubusercontent.com/98105177/216765156-fb51bdc0-1c0b-4d21-a668-3b7f44c0b2f3.png)

I did manage now to enable logging as I was not able to do that correctly before. The ZHA bridge would than fail to set up.

So here are the logs of my latest attemp:
[home-assistant_2023-02-04T11-32-50.696Z.log](https://github.com/jacekk015/zha_quirks/files/10608514/home-assistant_2023-02-04T11-32-50.696Z.log)

**Comment by malfunctioningEddy** [comment]
From what I can see in the log in failes to initialize:
2023-02-04 12:28:00.065 WARNING (MainThread) [zigpy.device] Device <Device model='TS0601' manuf='_TZE200_sur6q7ko' nwk=0x6F46 ieee=84:71:27:ff:fe:c6:c4:c0 is_initialized=True> failed to initialize due to unexpected error

**Comment by jacekk015** [comment]
@malfunctioningEddy
Bug was corrected.
Download quirk again.
https://github.com/jacekk015/zha_quirks/blob/main/ts0601_trv_zonnsmart.py

**Comment by malfunctioningEddy** [comment]
@jacekk015 
Right! :)
![firefox_G3N2m0mwa8](https://user-images.githubusercontent.com/98105177/216788114-12efb670-0904-44ce-bff9-e714a76f3d31.png)
![firefox_HsQShckWwt](https://user-images.githubusercontent.com/98105177/216788119-3055c7cc-4816-4474-a938-86c692e19abb.png)

That looks very good thanks!

First time I got the device in this state so I will start playing with it now.

Again thanks very much!

**Comment by malfunctioningEddy** [comment]
First thoughts:
- Battery 100% does not seem very good as I've had these batteries in there for a while now and manualy operating the device.
- Controls: thermostat shows the current temp now bit I can't seem to set a setpoint temperature. Though I don't know if I should. 
- In the dashboard card I am able to set the device to "heating" and "idle" which actually work well. But I would think I could set a target temperature and the device would "heat" or "idle" untill it reaches the target temp.

What do you think?

**Comment by jacekk015** [comment]
Did some fixing now. Download newer file.
Firstly - without logs I can't say anything, but:
1) Battery - TRV's are sometimes strange. Not every TRV report battery level each percent. Sometimes it's 100% and next 0%. That's what your TRV do. Treat it more like battery low warning.
2) You should have possibility when you click Thermostat on Controls panel.
3) Your TRV actually supported enable/disable function - eventually users reported that.
There are two things:
- system mode: on/off
- state: heating/idle
You are controlling system mode.
For state we need an information from TRV. Unfortunately your TRV doesn't send any valve state, so we don't know when it is heating or idle.

**Comment by malfunctioningEddy** [comment]
@jacekk015 
Thanks for all your help.

- I uploaded new file 
- Deleted device
- Reboot HA
- Added device again

Now showing as an unknon manufacturer:
![firefox_OqgY8Ia09U](https://user-images.githubusercontent.com/98105177/216791255-8d2f25f1-012a-4102-b1f1-b1df799922cc.png)
After reset it's better (don't know why):
![firefox_8uBMLdGGXH](https://user-images.githubusercontent.com/98105177/216791282-f09886aa-07f9-4c2a-aa5e-0dc49e69d89c.png)
Thermostat control look better as well, I have setpoint!
![firefox_NmlM4eYamH](https://user-images.githubusercontent.com/98105177/216791312-b415892b-633f-4d3f-8e55-20c56c8b6d5f.png)

When I lower setpoint the valve closes which is good. However the state remains "Heating":
![firefox_Te3CHK2uDj](https://user-images.githubusercontent.com/98105177/216791447-3183b62d-7722-4efb-a292-6fab04291f0c.png)

Added logs:
[home-assistant_2023-02-04T22-06-00.438Z.log](https://github.com/jacekk015/zha_quirks/files/10609759/home-assistant_2023-02-04T22-06-00.438Z.log)

**Comment by jacekk015** [comment]
As I wrote above. Your TRV device doesn't report any valve opening.
That image you've posted doesn't state that TRV is heating or idle.
That's system mode: Heating as a function. It can be Heating or Off.
That card is an Thermostat card and Thermostat can Heat or Cool or be Off.
Air conditioner can Heat, Cool, Dry and etc...

Take a look at my Air conditioner card.
Second to the left is a flame icon - that's what yours Heating is - a function/mode.
![image](https://user-images.githubusercontent.com/14165726/216823056-695921f4-6143-4713-b9a9-c11023d91d06.png)

To check state you need to look at device view - because it's not the same:
![image](https://user-images.githubusercontent.com/14165726/216823319-d1741018-d0e2-4ebc-96eb-ecd2c4ad29c8.png)

Moreover since your TRV doesn't report Heating/Idle state it can only be faked by the quirk code.
My TRV also doesn't report Heating/Idle state.
I made for myself simplest thing I can do:
When the room temp < temp set - state Heating
When the room temp >= temp set - state Idle
That doesn't show exact real state but it's better to have something.

Some users checked their hysteresis on the device so we've shifted that idle +/- according to their needs.

**Comment by malfunctioningEddy** [comment]
Hi,

Thanks for explaining all this. 
I did more testing and added another tvr to the system:
![image](https://user-images.githubusercontent.com/98105177/217218552-65ad1a46-3b40-48ba-a671-8340855716a6.png)

Strange thing is that the second one does not have the same icons as the first one, which is a little weird. It does work fine though by setting target temperature.
What I found is that the original app has some more features like child lock which aren't standard available in HA. By Device Mangement so I guess it's available by scripting:
![image](https://user-images.githubusercontent.com/98105177/217219223-ff9949e8-f30d-4897-a3b5-7e8f4f57b48b.png)

Again, thanks for all the work on this.

**Comment by jacekk015** [comment]
Device probably has more features. We often add child lock as a switch in HA. I can do it later.
As for other features - often plenty of them are added... it takes time... and they aren't used.
Like for example open window detection which for 99% of times doesn't work properly and no one can rely on that feature.
Test showed that you need to put a TRV in the freezer to make that function work. Room temp drop is too slow - probably.

As for icons - they should be exact same. That code wasn't 100% written by me from the beginning - later will take a look what happens here.

**Comment by jacekk015** [comment]
After file replace and restart new switch should be available - that's child lock.

**Comment by malfunctioningEddy** [comment]
Thanks very much. I will run tests tomorrow.

**Comment by malfunctioningEddy** [comment]
@jacekk015 
Hi the integration failed to initialize, had to revert back to previous version:
![afbeelding](https://user-images.githubusercontent.com/98105177/217666499-4f034dae-a4f2-4ddb-a2b5-991fde6c8e40.png)

Logs:
[home-assistant_2023-02-08T19-10-45.744Z.log](https://github.com/jacekk015/zha_quirks/files/10690414/home-assistant_2023-02-08T19-10-45.744Z.log)

**Comment by jacekk015** [comment]
Small bug - fixed in repo.

**Comment by malfunctioningEddy** [comment]
Hi,

Now works better. I removed both TVRs from HA and re-added them.
![firefox_OgH05JWiQT](https://user-images.githubusercontent.com/98105177/218321936-21900779-bb62-44a4-b738-2ee35b612350.png)

Child lock is working perfectly!

However I still have the difference in icons between the two TVRs:
![afbeelding](https://user-images.githubusercontent.com/98105177/218322028-b1b5d003-3085-4002-9c49-ca530452226b.png)
![afbeelding](https://user-images.githubusercontent.com/98105177/218322041-167cc4f2-70c4-4b61-9997-d8a9de687028.png)

They both have the same zigbee device id: TS0601 by _TZE200_sur6q7ko.

I'm not sure if they have the same firmware though. I connected one of them temporarily to the LSC Smart Connect app to check which options they had. Maybe that app updated the formware of that TVR.

Is there any way we can retrieve the firmware using ZHA?
